// eslint-disable react/jsx-props-no-spreading
// eslint-disable jsx-props-no-spreading
import "../styles/globals.css";

import environment from "config/relay/environment";
import theme from "config/theme";
import type { AppProps } from "next/app";
import Head from "next/head";
import { SnackbarProvider } from "notistack";
import { RelayEnvironmentProvider } from "react-relay/hooks";

import { ThemeProvider } from "@mui/system";

function MetaTags() {
  return (
    <Head>
      <meta name="description" content="Generated by create todo app" />
      <meta name="viewport" content="initial-scale=1, width=device-width" />
    </Head>
  );
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <MetaTags />
      <RelayEnvironmentProvider environment={environment}>
        <ThemeProvider theme={theme}>
          <SnackbarProvider>
            <Component {...pageProps} />
          </SnackbarProvider>
        </ThemeProvider>
      </RelayEnvironmentProvider>
    </>
  );
}

export default MyApp;
