// eslint-disable react/jsx-props-no-spreading
// eslint-disable jsx-props-no-spreading
import "../styles/globals.css";

import {
  AUTH_CLIENT_ID,
  AUTH_DOMAIN,
} from "_constants";
import environment from "config/relay/environment";
import theme from "config/theme";
import type { AppProps } from "next/app";
import Head from "next/head";
import { SnackbarProvider } from "notistack";
import { RelayEnvironmentProvider } from "react-relay/hooks";

import { Auth0Provider } from "@auth0/auth0-react";
import { ThemeProvider } from "@mui/system";

function MetaTags() {
  return (
    <Head>
      <meta name="description" content="Generated by create todo app" />
      <meta name="viewport" content="initial-scale=1, width=device-width" />
    </Head>
  );
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <MetaTags />
      <RelayEnvironmentProvider environment={environment}>
        <ThemeProvider theme={theme}>
          <Auth0Provider
            domain={AUTH_DOMAIN}
            clientId={AUTH_CLIENT_ID}
            audience="todo-next"
            redirectUri={
              typeof window !== "undefined"
                ? window.location.origin
                : "http://localhost:3000"
            }
          >
            <SnackbarProvider>
              <Component {...pageProps} />
            </SnackbarProvider>
          </Auth0Provider>
        </ThemeProvider>
      </RelayEnvironmentProvider>
    </>
  );
}

export default MyApp;
